# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_gz_controller
    - right_arm_gz_controller

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - l1
      - l2
      - l3_1
      - l3_roll_joint
      - l3_pitch_joint
      - l3_yaw_joint
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - r1
      - r2
      - r3_1
      - r3_roll_joint
      - r3_pitch_joint
      - r3_yaw_joint